language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.5
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - 2.2.4
  - 2.2.5
  - 2.3.0
  - 2.3.1
env:
  - "RAILS_VERSION=4.2.0"
notifications:
  email:
    recipients:
      - 60tonangel@gmail.com
    on_success: change
    on_failure: change
