language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
env:
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=5.0.0"
  - "RAILS_VERSION=5.1.0"
  - "RAILS_VERSION=5.2.0"
  - "RAILS_VERSION=6.0.0"
matrix:
  exclude:
    - rvm: 2.0
      env: "RAILS_VERSION=5.0.0"
    - rvm: 2.0
      env: "RAILS_VERSION=5.1.0"
    - rvm: 2.0
      env: "RAILS_VERSION=5.2.0"
    - rvm: 2.0
      env: "RAILS_VERSION=6.0.0"
    - rvm: 2.1
      env: "RAILS_VERSION=5.0.0"
    - rvm: 2.1
      env: "RAILS_VERSION=5.1.0"
    - rvm: 2.1
      env: "RAILS_VERSION=5.2.0"
    - rvm: 2.1
      env: "RAILS_VERSION=6.0.0"
    - rvm: 2.2
      env: "RAILS_VERSION=5.0.0"
    - rvm: 2.2
      env: "RAILS_VERSION=5.0.0"
    - rvm: 2.3
      env: "RAILS_VERSION=6.0.0"
    - rvm: 2.4
      env: "RAILS_VERSION=4.2.0"
    - rvm: 2.4
      env: "RAILS_VERSION=6.0.0"

notifications:
  email:
    recipients:
      - 60tonangel@gmail.com
    on_success: change
    on_failure: change
